services:
  php:
    image: php:8.2-apache
    container_name: php-container
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
    command: bash -c "docker-php-ext-install mysqli && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: school_management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: db           # Links phpMyAdmin to the MySQL container
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"             # Exposes phpMyAdmin on port 8081
    depends_on:
      - db

networks:
  mysql-phpmyadmin:
    driver: bridge

volumes:
  db_data: